name = "profile-backend"
main = "src/index.js"
compatibility_date = "2025-11-01"

[[d1_databases]]
binding = "profile_db"
database_name = "hyperme"
database_id = "17f1ae91-9fac-41cc-8b41-46659aa66bde"

[[r2_buckets]]
binding = "PROFILE_BUCKET"
bucket_name = "profile-storage"

routes = [
  { pattern = "*.profile.io.vn", custom_domain = true }
]

logpush = true
